// Generated by ts-to-zod
import { z } from "zod";
import { PostOrderResponseStatus, OrderStatus, SettlementType } from "./types";

export const chainSchema = z
  .string()
  .describe(
    "Chain identifier following CAIP-2 standard (namespace:reference format).\nFor EVM chains, uses eip155 namespace with chain ID.",
  );

export const nativeAddressSchema = z
  .string()
  .describe(
    "Native blockchain address in its canonical format for the specified chain.\nFormat varies by chain namespace.",
  );

export const chainAddressSchema = z.object({
  chain: chainSchema.describe(
    "The blockchain network identifier in CAIP-2 format (namespace:reference)",
  ),
  address: nativeAddressSchema.describe(
    "The address in its native format for the specified chain",
  ),
});

export const amountSchema = z
  .string()
  .regex(/^[0-9]+$/)
  .describe(
    "Token amounts are encoded as decimal strings to preserve precision for large integers\n(e.g., uint256). Always represents the smallest unit of the token (wei for ETH,\nsatoshi for BTC, etc.). No decimals or scientific notation allowed.",
  );

export const swapTypeSchema = z
  .union([z.literal("exact-input"), z.literal("exact-output")])
  .describe(
    'Defines which amount is fixed in a quote request when one amount is undefined.\n- "exact-input": User specifies exact input amount, provider quotes the output amount\n- "exact-output": User specifies exact output amount, provider quotes the input amount needed',
  )
  .default("exact-input");

export const assetLockReferenceSchema = z.object({
  kind: z
    .union([z.literal("the-compact"), z.literal("rhinestone")])
    .describe(
      'The locking protocol to use for securing assets\n- "the-compact": The Compact protocol for efficient cross-chain transfers\n- "rhinestone": Rhinestone modular account abstraction framework',
    ),
  params: z
    .record(
      z
        .unknown()
        .describe(
          "Additional configuration parameters specific to the chosen lock type",
        ),
    )
    .optional()
    .describe(
      "Additional configuration parameters specific to the chosen lock type",
    ),
});

export const originSubmissionSchema = z.object({
  mode: z
    .union([z.literal("user"), z.literal("protocol")])
    .describe(
      'Determines transaction submission responsibility\n- "user": User directly submits and pays gas\n- "protocol": Protocol/relayer submits on user\'s behalf (gasless for user)',
    ),
  schemes: z
    .array(
      z.union([
        z.literal("erc-4337"),
        z.literal("permit2"),
        z.literal("erc20-permit"),
        z.literal("eip-3009"),
      ]),
    )
    .optional()
    .describe(
      'List of supported authorization methods for the transaction\n- "erc-4337": Account abstraction (smart contract wallets)\n- "permit2": Uniswap\'s Permit2 for token approvals\n- "erc20-permit": EIP-2612 permit for gasless approvals\n- "eip-3009": Transfer with authorization (e.g., USDC)',
    ),
});

export const inputSchema = z.object({
  user: chainAddressSchema.describe(
    "The CAIP-350 address of the user providing the input assets",
  ),
  asset: chainAddressSchema.describe(
    "The CAIP-350 address of the token/asset being provided as input",
  ),
  amount: amountSchema
    .optional()
    .describe(
      "For quote requests:\n- exact-input: The exact amount user will provide\n- exact-output: minimum amount user will provide. Optional in request for open discovery of the quote\nFor direct intents: Always specified",
    ),
  lock: assetLockReferenceSchema
    .optional()
    .describe("Locking mechanism to use for securing the input assets"),
});

export const outputSchema = z.object({
  receiver: chainAddressSchema.describe(
    "The CAIP-350 address that will receive the output assets",
  ),
  asset: chainAddressSchema.describe(
    "The CAIP-350 address of the token/asset to be received as output",
  ),
  amount: amountSchema
    .optional()
    .describe(
      "For quote requests:\n- exact-input: minimum amount user wants to receive. Optional in request for open discovery of the quote\n- exact-output: The exact amount user wants to receive\nFor direct intents: Always specified",
    ),
  calldata: z
    .string()
    .optional()
    .describe(
      "Encoded function call to be executed when delivering the output,\nenabling composability with other protocols",
    ),
});

export const quotePreviewSchema = z.object({
  inputs: z.array(inputSchema),
  outputs: z.array(outputSchema),
});

export const quotePreferenceSchema = z
  .union([
    z.literal("price"),
    z.literal("speed"),
    z.literal("input-priority"),
    z.literal("trust-minimization"),
  ])
  .describe(
    'Indicates user\'s priority when selecting between multiple quotes\n- "price": Optimize for best exchange rate/lowest cost\n- "speed": Optimize for fastest execution time\n- "input-priority": Prefer quotes that use inputs in the order specified\n- "trust-minimization": Prefer quotes with strongest security guarantees',
  );

export const failureHandlingModeSchema = z
  .union([
    z.literal("refund-automatic"),
    z.literal("refund-claim"),
    z.literal("needs-new-signature"),
  ])
  .describe(
    'Defines how to handle transaction failures or partial fills\n- "refund-automatic": Automatic refund on failure without user action\n- "refund-claim": User must claim refund manually after failure\n- "needs-new-signature": Requires new user signature to retry or refund',
  );

export const getQuoteRequestSchema = z.object({
  user: chainAddressSchema,
  intent: z.object({
    intentType: z.literal("oif-swap"),
    inputs: z.array(inputSchema),
    outputs: z.array(outputSchema),
    swapType: swapTypeSchema
      .optional()
      .describe("Determines which amounts are fixed vs quoted")
      .default("exact-input"),
    minValidUntil: z.number().optional(),
    preference: quotePreferenceSchema.optional(),
    originSubmission: originSubmissionSchema.optional(),
    failureHandling: z.array(failureHandlingModeSchema).optional(),
    partialFill: z.boolean().optional(),
    metadata: z.record(z.any()).optional(),
  }),
  supportedTypes: z.array(z.string()),
});

export const eIP712TypePropertySchema = z.object({
  name: z.string(),
  type: z.string(),
});

export const eIP712TypesSchema = z
  .record(
    z
      .array(eIP712TypePropertySchema)
      .describe("Map from type name to its field definitions, per EIP-712"),
  )
  .describe("Map from type name to its field definitions, per EIP-712");

export const oifResourceLockOrderSchema = z.object({
  type: z.literal("oif-resource-lock-v0"),
  payload: z.object({
    signatureType: z.literal("eip712"),
    domain: z.record(z.any()),
    primaryType: z.string(),
    message: z.record(z.any()),
    types: eIP712TypesSchema,
  }),
});

export const oif3009OrderSchema = z.object({
  type: z.literal("oif-3009-v0"),
  payload: z.object({
    signatureType: z.literal("eip712"),
    domain: z.record(z.any()),
    primaryType: z.string(),
    message: z.record(z.any()),
    types: eIP712TypesSchema,
  }),
  metadata: z.record(z.any()),
});

export const postOrderResponseStatusSchema = z.nativeEnum(
  PostOrderResponseStatus,
);

export const postOrderResponseSchema = z.object({
  orderId: z.string().optional(),
  status: postOrderResponseStatusSchema,
  message: z.string().optional(),
  order: z.record(z.unknown()).optional(),
});

export const orderStatusSchema = z.nativeEnum(OrderStatus);

export const assetAmountSchema = z.object({
  asset: chainAddressSchema.describe(
    "The token/asset identifier with chain information",
  ),
  amount: amountSchema
    .optional()
    .describe("Token amount in smallest unit (wei, satoshi, etc.)"),
});

export const settlementTypeSchema = z.nativeEnum(SettlementType);

export const settlementSchema = z.object({
  type: settlementTypeSchema.describe(
    "The type of settlement mechanism used for this order",
  ),
  data: z
    .record(
      z
        .unknown()
        .describe("Additional parameters specific to the settlement type"),
    )
    .describe("Additional parameters specific to the settlement type"),
});

export const getOrderRequestSchema = z.object({
  id: z.string().describe("Unique ID assigned to the order upon submission"),
});

export const getOrderResponseSchema = z.object({
  id: z.string(),
  status: orderStatusSchema,
  createdAt: z.number(),
  updatedAt: z.number(),
  quoteId: z.string().optional(),
  inputAmounts: z.array(assetAmountSchema),
  outputAmounts: z.array(assetAmountSchema),
  settlement: settlementSchema,
  fillTransaction: z.record(z.unknown()).optional(),
});

export const assetInfoSchema = z.object({
  address: chainAddressSchema.describe(
    "Asset address in CAIP-350 format for cross-chain compatibility.",
  ),
  symbol: z
    .string()
    .describe(
      'Asset symbol for display purposes (e.g., "USDC", "WETH", "USDT")',
    ),
  decimals: z
    .number()
    .describe("Asset decimal precision (e.g., 6 for USDC, 18 for WETH)"),
});

export const networkAssetsSchema = z.object({
  chain: chainSchema.describe(
    "Chain identifier in CAIP-2 format (namespace:reference)",
  ),
  assets: z
    .array(assetInfoSchema)
    .describe("Array of assets supported on this network"),
});

export const getAssetsResponseSchema = z.object({
  networks: z
    .record(
      chainSchema.describe(
        'Map where keys are CAIP-2 chain identifiers (e.g., "eip155:1", "eip155:137") and\nvalues are network asset configurations',
      ),
      networkAssetsSchema.describe(
        'Map where keys are CAIP-2 chain identifiers (e.g., "eip155:1", "eip155:137") and\nvalues are network asset configurations',
      ),
    )
    .describe(
      'Map where keys are CAIP-2 chain identifiers (e.g., "eip155:1", "eip155:137") and\nvalues are network asset configurations',
    ),
});

export const oifEscrowOrderSchema = z.object({
  type: z.literal("oif-escrow-v0"),
  payload: z.object({
    signatureType: z.literal("eip712"),
    domain: z.record(z.any()),
    primaryType: z.string(),
    message: z.record(z.any()),
    types: eIP712TypesSchema,
  }),
});
